### PR TITLE
Implement most of the Data.Array API

### PR DESCRIPTION
**Pull request by gabejohnson**
See https://github.com/funkia/list/pull/27

I've included the license notice from `-arrays` as the API and documentation are copied from it.

I still think it's a good idea to include some example usage, but I didn't want to copy those. It'd make sense to include algorithmic complexity as well for each function.

### CODE REVIEW

**Comment by paldepind** [comment]
Is `updateAtIndices` and `modifyAtIndices` the only functions missing from the `Data.Array` API?

> I still think it's a good idea to include some example usage, but I didn't want to copy those. It'd make sense to include algorithmic complexity as well for each function.

Definitely. I can go over the functions and add running time and adapt examples from the List documentation?

**Comment by gabejohnson** [comment]
> Is `updateAtIndices` and `modifyAtIndices` the only functions missing from the Data.Array API?

I believe so. I wanted to discuss whether you wanted to include them or not. They seem fairly specialized and wouldn't be useful for anything other than _very_ large lists IMO.

> Definitely. I can go over the functions and add running time and adapt examples from the List documentation?

Great!

**Comment by paldepind** [comment]
> I believe so. I wanted to discuss whether you wanted to include them or not. They seem fairly specialized and wouldn't be useful for anything other than very large lists IMO.

I agree. They seem like a small optimization mainly as they can utilize internal mutations. But, I think they're important to have just so we can say "Implements ~~most of~~ the Data.Array API".

**Comment by paldepind** [comment]
I'll merge this 😄 

I'll add `updateAtIndices` and `modifyAtIndices` when I get the time.

If you'd like to help maintain the package @gabejohnson let me know and I'll give you access to the repository.

**Pull request merged**
