### PR TITLE
Modernize rrb list

### PR DESCRIPTION
**Pull request by TorNATO-PRO**
# Changes

- Removed dependency on Bower and Pulp, moved to Spago.
- Changed CommonJS imports to use ES6 instead.
- Added QuickCheck for a couple of test cases - using `Data.Array` as the Oracle.
- Added purescript-psa for error reporting and persistence.

### CODE REVIEW

**Comment by paldepind** [comment]
Thank you for the PR. The work looks really good (I'm a bit out of touch with PureScript but it seems that way 😅).

Is the PR ready to be merged? 🙂

**Comment by TorNATO-PRO** [comment]
Hi Simon!

Yes, I just pushed some changes to more closely match the `Data.Arrays` library. I think it should be good to merge now, seems to pass all the regression tests and tests I added for my changes.

**Comment by TorNATO-PRO** [comment]
@paldepind are you able to merge this

**Comment by paldepind** [comment]
Thanks for the reminder, I completely forgot about it.

Thanks a lot for the pull request and the great work.

Is there anything I should do to get the package published in the Spago registry or, alternatively, any rights that I should give you such that you can do it?

**Comment by TorNATO-PRO** [comment]
> Thanks for the reminder, I completely forgot about it.
> 
> Thanks a lot for the pull request and the great work.
> 
> Is there anything I should do to get the package published in the Spago registry or, alternatively, any rights that I should give you such that you can do it?

Hi @paldepind, I just opened another PR which includes an update to the `spago.yaml` and instructions for updating it with their registry.

**Pull request merged**
